### ISSUE TITLE
Can you explain the setup?

### ISSUE THREAD

**Issue by ericyip** [now-examples/wordpress#1]
Hi, I would like to test the deployment via now.
How to wire remote database with this?

**Comment by jsvde** [comment]
Edit the environment variables in the now.json file.
See [now.json env](https://zeit.co/blog/now-json#`env`-(object)).

**Comment by maitret** [comment]
Can you explain? 
`{
  "dotenv": true,
  "env": [
    "DB_HOST",
    "DB_NAME",
    "DB_USER",
    "DB_PASSWORD",
    "SENDGRID_API_KEY",
    "SENDGRID_FROM_NAME",
    "SENDGRID_FROM_EMAIL"
  ]
}`

**Comment by coetry** [comment]
When you enter `now` in the project directory, you will be prompted to enter DB_HOST, DB_NAME ... one line at a time. If you have a MySQL database server hosted somewhere like Google Cloud Platform, then you can enter the DB details accordingly.
